#!/bin/bash
################################################################################
#                                                                              #
# blackarchinstall - Blackarch Install                                         #
#                                                                              #
# FILE                                                                         #
# blackarchinstall.sh                                                          #
#                                                                              #
# DATE                                                                         #
# 2013-12-16                                                                   #
#                                                                              #
# DESCRIPTION                                                                  #
# Script for easy install                                                      #
#                                                                              #
# AUTHOR                                                                       #
# nrz@nullsecurity.net                                                         #
#                                                                              #
################################################################################

# SECURITY VAR - this version can rm -rf /* your hard drive
SEC_ENABLE="true"


# root variable
ROOT="/mnt/blackarch"

# BA REPO
BLACKARCH_REPO_URL='http://www.blackarch.org/blackarch/$repo/os/$arch'

# Defaults Partitioning
HD="/dev/sda"
boot_part="${HD}" # next to fix - parsing fdisk
boot_type="ext2"
boot_size="100MB"
root_part="${HD}"
root_type="ext4"
root_size="10GB"

# Partition CONST
PART_AUTO="1"
PART_MANUAL="2"

# blackarchinstall version
VERSION="v0.3beta"

# true / false
FALSE="0"
TRUE="1"

# return codes
SUCCESS="1337"
FAILURE="31337"

# verbose mode - default: quiet
VERBOSE="/dev/null"

# colors
WHITE="$(tput bold ; tput setaf 7)"
GREEN="$(tput setaf 2)"
RED="$(tput bold; tput setaf 1)"
YELLOW="$(tput bold ; tput setaf 3)"
NC="$(tput sgr0)" # No Color


wprintf() {
    fmt=$1
    shift
    printf "%s${fmt}%s\n" "${WHITE}" "$@" "${NC}"

    return "${SUCCESS}"
}

# print warning
warn()
{
    printf "%s[!] WARNING: %s%s\n" "${RED}" "${*}" "${NC}"

    return "${SUCCESS}"
}

# print error and exit
err()
{
    printf "%s[-] ERROR: %s%s\n" "${RED}" "${*}" "${NC}"

    return "${SUCCESS}"
}

# print error and exit
cri()
{
    printf "%s[-] CRITICAL: %s%s\n" "${RED}" "${*}" "${NC}"

    exit "${FAILURE}"
}


# usage and help
usage()
{
cat <<EOF
Usage: $0 <arg> | <misc>
MISC:
    -V: print version and exit
    -H: print help and exit
EOF
    return "${SUCCESS}"
}

# leet banner, very important
banner()
{
    printf "%s--==[ BlackArch Install %s ]==--%s\n" "${YELLOW}" "${VERSION}" "${NC}"

    return "${SUCCESS}"
}

check_env()
{
    if [ -f /var/lib/pacman/db.lck ]; then
        cri "Pacman locked - rm /var/lib/pacman/db.lck"
    fi
}

# check argument count
check_argc()
{
    return "${SUCCESS}"
}

# check if required arguments were selected
check_args()
{
    return "${SUCCESS}"
}


update_system()
{
    if [ "$(uname -m)" == "x86_64" ]; then
        wprintf "[+] Enabling multilib"
        printf "[multilib]\nInclude = /etc/pacman.d/mirrorlist\n" >> /etc/pacman.conf
    fi

    pacman -Syy

    #fix this
    #sed -i '/[multilib]/{ s/^#//; n; s/^#//; }' /etc/pacman.conf

    return "${SUCCESS}"
}

setup_partition_values()
{
    part_opt=${1}

    # * BOOT
    # Manual
    if [ "${part_opt}" == "${PART_MANUAL}" ]; then
        # boot partition
        printf "[+] Select partition number for /boot partition [%s1]: " "${HD}"
        read a; [ "${a}" != "" ] && boot_part=${a}
        printf "[+] Select device type for %s [%s]: " "${boot_part}" "${boot_type}"
        read a; [ "${a}" != "" ] && boot_type=${a}
    fi

    # Manual && Automatic
    printf "[+] Select partition size for /boot [%s]: " "${boot_size}"
    read a; [ "${a}" != "" ] && boot_size=${a}

    # * ROOT
    # Manual
    if [ "${part_opt}" == "${PART_MANUAL}" ]; then
        # root partition
        printf "[+] Select partition number for / partition [%s2]: " "${HD}"
        read a; [ "${a}" != "" ] && root_part=${a}
        printf "[+] Select device type for %s [%s]: " "${root_part}" "${root_type}"
        read a; [ "${a}" != "" ] && root_type=${a}
    fi

    # Manual && Automatic
    printf "[+] Select partition size for / [%s]: " "${root_size}"
    read a; [ "${a}" != "" ] && root_size=${a}

    return "${SUCCESS}"
}

check_parted_status()
{
    [ ${?} != "0" ] && cri "Something wrong with parted"

    return "${SUCCESS}"
}

format_filesystem()
{
    # about to format
    printf "%s" "${RED}"
    printf "\n[!!] About to format partitions:\n"
    printf "    -> /boot %s - Size: %s\n" "${boot_part}" "${boot_size}"
    printf "    -> /     %s - Size: %s\n" "${root_part}" "${root_size}"
    printf "Are you sure? [y/N]: "; read a
    [ "${a}" == "y" ] || [ "${a}" == "Y" ] && printf "R3ally? ;) \n[y/N]: "; read a
    printf "%s" "${WHITE}"

    if [ "${a}" == "y" ] || [ "${a}" == "Y" ]; then

        # check if Partition Table already set
        # parted "/dev/${HD}" print | grep -q "Partition Table"
        parted -s "${HD}" mklabel msdos
        check_parted_status

        parted -a optimal "${boot_part}" mkpart primary 0% "${boot_size}"
        check_parted_status

        # partition bootable
        parted "${boot_part}" set 1 boot on
        check_parted_status

        parted -a optimal "${root_part}" mkpart primary "${boot_size}" "${root_size}"
        check_parted_status

        "mkfs.${boot_type}" -L boot "${boot_part}1"
        "mkfs.${boot_type}" -L root "${root_part}2"

        printf "[+] Created boot partition: %s - ext2\n" "${boot_part}"
        printf "[+] Created root partition: %s - ext4\n" "${root_part}"
    else
        # go back to setup up filesystem
        setup_filesystem
        return "${SUCCESS}"
    fi

    return "${SUCCES}"
}

setup_filesystem()
{
    # TODO: add swap

    printf "%s" "${WHITE}"


    # user input settings
    printf "[+] Type the device for install [%s]: " "${HD}"
    read a; [ "${a}" != "" ] && HD=${a} # sanitize input

    printf "    -> Hard Drive Selected: %s\n" "${HD}"

    while ! [ "${part_opt}" == "${PART_AUTO}" -o "${part_opt}" == "${PART_MANUAL}" ]; do
        printf "[+] Partition mode:\n"
        printf "%s[WARNING] If this is a real env (not a Virtual Machine):\n" "${RED}"
        printf " * We recomend you to make partitioning by hand before any install and choose option 2.\n"
        printf " * This comes with no guarantees after option 1. You had been warned. ;)\n%s" "${WHITE}"
        printf "    1. Automatic - new partition will be created next to your actual ones\n"
        printf "    2. Manual - you have already partitioned your HD\n"
        printf "Make your choice: "; read part_opt
    done

    setup_partition_values "${part_opt}"
    [ "${part_opt}" == "${PART_AUTO}" ] && format_filesystem

    printf "%s" "${NC}"

    return "${SUCCESS}"
}

mount_filesystem()
{

    mkdir -p "${ROOT}"
    mount -t "${root_type}" "${HD}2" "${ROOT}"
    mkdir -p "${ROOT}/boot"
    mount -t "${boot_type}" "${HD}1" "${ROOT}/boot"

    return "${SUCCESS}"
}

install_base_packages()
{
    wprintf "  --> ArchLinux Base"
    pacstrap -c "${ROOT}" base

    return "${SUCCESS}"
}

install_chroot()
{
    mode=${1}
	chroot_file="chroot-install"

    cp "${chroot_file}" "${ROOT}/bin"

    mount -t proc proc "${ROOT}/proc"
    mount --rbind /dev "${ROOT}/dev"
    mount --rbind /sys "${ROOT}/sys"

    chroot "${ROOT}" "${chroot_file}" "${mode}" -d "${HD}"

    # cleaning up
    rm -rf "${ROOT}/bin/${chroot_file}"

    return "${SUCCESS}"
}

install()
{
    menu_opt=${1}

    wprintf "[+] Updating system..."
    update_system

    wprintf "[+] Hard drive configuration..."
    setup_filesystem

    wprintf "[+] Mounting filesystem..."
    mount_filesystem

    wprintf "[+] Installing packages..."
    install_base_packages

    wprintf "[+] Generating fstab..."
    genfstab -p "${ROOT}" >> "${ROOT}/etc/fstab"

    wprintf "[+] Generating pacman.conf"
    cp -Rf /etc/pacman* "${ROOT}/etc/"

    wprintf "[+] Generating resolv.conf"
    cp /etc/resolv.conf "${ROOT}/etc/"

    wprintf "[+] Setting up grub config..."
    cp grub/splash.png "${ROOT}/boot/"

    wprintf "[+] Installing chroot system..."

    case "${menu_opt}" in
        "1")
            err "Not Implemented Yet"
            ;;
        "2")
            install_chroot "-r"
            ;;
        "3")
            install_chroot "-b"
            ;;
    esac

    return "${SUCCESS}"
}

# parse command line options
get_opts()
{
    while getopts vVH flags
    do
        case "${flags}" in
            #i)
            #    #optarg=${OPTARG}
            #    opt="install"
            #    ;;
            v)
                VERBOSE="/dev/stdout"
                ;;
            V)
                printf "%s\n" "${VERSION}"
                exit "${SUCCESS}"
                ;;
            H)
                usage
                ;;
            *)
                err "WTF?! mount /dev/brain"
                ;;
        esac
    done

    return "${SUCCESS}"
}

install_menu()
{
    printf "%s" "${WHITE}"
    while ! [ "${menu_opt}" == "1" -o "${menu_opt}" == "2" -o "${menu_opt}" == "3" ]; do
        printf "[+] Select Install Mode:\n"
        printf "    1. Install from LiveCD.\n"
        printf "    2. Install from BlackArch Official Repository.\n"
        printf "    3. Install from Blackman.\n"
        printf "Make a choice: "; read menu_opt
        printf "%s"
    done

    printf "%s" "${NC}"

    return "${SUCCESS}"
}

# controller and program flow
main()
{
    banner
    check_argc ${*}
    get_opts ${*}
    check_args ${*}
    check_env

    # commented arg opt
    #if [ "${opt}" == "install" ]; then
        if [[ "${SEC_ENABLE}" == "false" ]]; then
            install_menu
            install "${menu_opt}"
        else
            cri "SEC_ENABLE var active - vim blackarch-install"
        fi
    #fi
    return "${SUCCESS}"
}


# program start
main ${*}

# EOF
